extends Control

var resolutions := [
	"360p: 640 x 360",
	"480p: 854 x 480",
	"720p: 1280 x 720",
	"1080p: 1920 x 1080",
	"1440p: 2560 x 1440",
	"3K: 3200 x 1800",
	"4K: 3840 x 2160",
	"5K: 5120 x 2880",
	"6K: 6144 x 3456",
	"7K: 7168 x 4032",
	"8K: 7680 x 4320",
	"9K: 9216 x 5184",
	"10K: 10240 x 5760",
	"11K: 11264 x 6336",
	"12K: 11520 x 6480",
	"13K: 13312 x 7488",
	"14K: 14336 x 8064",
	"15K: 14720 x 8280",
	"16K: 15360 x 8640",
	"17K: 16384 x 9216",
	"18K: 17280 x 9720",
	"19K: 18432 x 10368",
	"20K: 19200 x 10800",
	"21K: 20480 x 11520",
	"22K: 21840 x 12285"
]

var MAX_POPUP_Y_SIZE = 292
var DEFUALT_RESOLUTION_INDEX = 4
var MAX_IMAGE_PIXELS = 268435456

var extension = ".png"

func _ready() -> void:
	get_tree().paused = true

	for i in range(len(resolutions)):
		%resolutions_option_button.add_item(resolutions[i], i)

	%resolutions_option_button.selected = DEFUALT_RESOLUTION_INDEX

	var popup : PopupMenu = %resolutions_option_button.get_popup()
	popup.max_size.y = MAX_POPUP_Y_SIZE

	$FileDialog.current_dir = OS.get_system_dir(OS.SYSTEM_DIR_PICTURES)
	

func _exit_tree() -> void:
	get_tree().paused = false


func _process(_delta: float) -> void:
	%accept_button.disabled = !is_valid_file_name(%name_line_edit.text) or !is_folder_path_valid(%path_line_edit.text)


# This funcion was entirely generated by a Chatbot AI
func is_valid_file_name(file_name: String) -> bool:
	if file_name.strip_edges() == "":
		return false
		
	var regex = RegEx.new()
	regex.compile("[\\\\/:*?\"<>|]")
	if regex.search(file_name):
		return false
		
	var reserved_file_names = [
		"CON", "PRN", "AUX", "NUL", 
		"COM1", "COM2", "COM3", "COM4", "COM5", "COM6", "COM7", "COM8", "COM9",
		"LPT1", "LPT2", "LPT3", "LPT4", "LPT5", "LPT6", "LPT7", "LPT8", "LPT9"
	]
	if file_name.to_upper() in reserved_file_names:
		return false
		
	return true


func is_folder_path_valid(path: String) -> bool:
	return DirAccess.dir_exists_absolute(path) and path.strip_edges() != ""
	
# This funcion was entirely generated by a Chatbot AI
func render_image(width : float, height : float, path : String) -> void:
	if Global.current_shader_material == null or width * height >= MAX_IMAGE_PIXELS:
		return

	var canvas = RenderingServer.canvas_create()
	
	var canvas_item = RenderingServer.canvas_item_create()
	RenderingServer.canvas_item_set_parent(canvas_item, canvas)
	
	var material = Global.current_shader_material.duplicate()
	RenderingServer.canvas_item_set_material(canvas_item, material)

	var rect = Rect2(0, 0, width, height)
	RenderingServer.canvas_item_add_rect(canvas_item, rect, Color.WHITE)
	
	var viewport = RenderingServer.viewport_create()
	RenderingServer.viewport_set_size(viewport, width, height)
	RenderingServer.viewport_attach_canvas(viewport, canvas)
	RenderingServer.viewport_set_active(viewport, true)
	
	RenderingServer.viewport_set_update_mode(viewport, RenderingServer.VIEWPORT_UPDATE_ONCE)
	
	await RenderingServer.frame_post_draw
	
	var textura_rid = RenderingServer.viewport_get_texture(viewport)
	var imagen = RenderingServer.texture_2d_get(textura_rid)
	
	var error = imagen.save_png(path)
	if error != OK:
		print("Error saving: ", error)
		
	RenderingServer.free_rid(viewport)
	RenderingServer.free_rid(material)
	RenderingServer.free_rid(canvas_item)
	RenderingServer.free_rid(canvas)

	queue_free()
	

func get_vec2_resolution(index : int) -> Vector2:
	var text_split = resolutions[index].split(" ")
	return Vector2(int(text_split[1]), int(text_split[3]))


func _on_folder_button_pressed() -> void:
	$FileDialog.popup_centered()


func _on_file_dialog_dir_selected(dir: String) -> void:
	%path_line_edit.text = dir


func _on_cancel_button_pressed() -> void:
	queue_free()


func _on_accept_button_pressed() -> void:
	var res = get_vec2_resolution(%resolutions_option_button.selected)
	var path = %path_line_edit.text + "/" + %name_line_edit.text + extension

	if FileAccess.file_exists(path):
		$overwrite_dialog.visible = true
		return

	render_image(res.x, res.y, path)


func _on_overwrite_accept_button_pressed() -> void:
	var res = get_vec2_resolution(%resolutions_option_button.selected)
	var path = %path_line_edit.text + "/" + %name_line_edit.text + extension

	render_image(res.x, res.y, path)


func _on_overwrite_cancel_button_pressed() -> void:
	$overwrite_dialog.visible = false


func _on_extensions_option_button_item_selected(index: int) -> void:
	extension = %extensions_option_button.get_item_text(index)
